name: auto-commit

on:
  schedule:
    - cron: '0 2 * * 1-5'

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: auto-commit

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Make changes
        run: |
          echo "Last updated: $(date)" > last_updated.txt
          git add last_updated.txt

      - name: Commit changes
        run: git commit -m "Automated commit - $(date)" || echo "No changes to commit"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin HEAD
